export const appConfig = {
  url: "https://naveenautomationlabs.com/opencart/index.php?route=account/login",
  username: "gkalra88@gmail.com",
  password: "abc@1234",
  expectedMenuItems: [
    "Desktops",
    "Laptops & Notebooks",
    "Components",
    "Tablets",
    "Software",
    "Phones & PDAs",
    "Cameras",
    "MP3 Players",
  ],
  accountsPageLefftGridItems: [
    "My Account",
    "Edit your account information",
    "Change your password",
    "Modify your address book entries",
    "Modify your wish list",
    "My Orders",
    "View your order history",
    "Downloads",
    "Your Reward Points",
    "View your return requests",
    "Your Transactions",
    "Recurring payments",
    "My Affiliate Account",
    "Register for an affiliate account",
    "Newsletter",
    "Subscribe / unsubscribe to newsletter",
  ],
  searchItem: "Macbook",
};
